- name: copy file
  hosts: all
  tasks:
    - name: Copy file
      debug: 
        msg: "echo saludos"
    - name: Creating an empty file
      file:
        path: "/tmp/test.txt"
        state: touch
      become: yes
